### PR TITLE
Add linkedin support

### PR DESCRIPTION
**Pull request by paradoxengine**
I found myself wanting to have linkedin support in this great template, so there you go :)

### CODE REVIEW

**Comment by mikegsrv** [comment]
Highly recommend not to merge this PR as Google Analytics should be added for each user by himself and not globally as some users wouldn't accept tracking their site.

Theme should be abstracted as much as it should, so any case-relative should be ignored.

**Comment by paradoxengine** [comment]
Well, for one there is clear sloppiness on my side here.I meant to only add Linkedin support here but mistakenly added also other requests.

This said, unless I misunderstand how the framework works, analytics would only be injected if the appropriate optional configuration parameter is present. So it very much stays optional and abstract - I fully agree it would be madness to push this feature to every user.
 
I'm happy to split the 2 things if controversial or if only to keep the commit message sane.

**Comment by mikegsrv** [comment]
@paradoxengine, hello!

I see your point. I suppose, it's ok to add at least description of what this script does and mention it in PR header. 

Thanks!

**Comment by fncnt** [comment]
Hey @paradoxengine,
thanks a lot!
Please excuse my late reply, I was quite busy over the last weeks.

I just pushed a few commits addressing custom contact links in a more general manner.
Have a look at the updated [`README.md`](https://github.com/fncnt/vncnt-hugo#changing-contact-links).

Also, if you're interested in Tracking, [the internal templates](https://gohugo.io/templates/internal/#google-analytics) might be relevant for you.
I think I'd accept a new PR for Google Analytics if it uses the internal template and documents the usage in `README.md`.

**Comment by paradoxengine** [comment]
No problem at all, thanks for the improved social links and thanks for
pointing out the proper way add analytics support. Sent a new pull request
through.

Il giorno mer 6 mar 2019 alle ore 12:13 fncnt <notifications@github.com> ha
scritto:

**Pull request closed without merging**
